### PR TITLE
Cameron high icp edit

### PR DESCRIPTION
**Pull request by camerondeleone**
Add fork into onboarding flow to split out high ICP (+maybe a few other properties) before first email. The changes to the email will be 

> Hey there, Cameron here (engineer from Customer Success) 👋. 
> 
> I'll make this brief, since I'm sure you're excited to get started, but I wanted to let you know I'm available to help if/when you run into any roadblocks (with integration, pricing, analysis, dashboard setup, or if you just want to quickly chat through anything). You can reach me here, by email, or grab a quick 15 minute slot [here](https://calendly.com/cameron-posthog/15-minute-posthog-q-a) to chat.
> 
> If you're looking to get up and running asap, and have a website/app, we recommend installing our snippet and building an AARRR funnel to get a clear view of your user journey. We also have [other SDKs](https://posthog.com/docs/libraries) if browser js doesn't cover your use case. Let me know if you'd like to chat through which makes most sense for your use case.

Current email, for ref: 
image

### CODE REVIEW

**Review by joethreepwood — APPROVED** [review]
I've shortened the text a little to make it a bit quicker, and built this out into the flow. Let me know if you need any changes, otherwise this is now running: 

Screenshot 2023-12-05 at 10 51 04

(SDKs and Snippet are both available on the Install link)

**Comment by joethreepwood** [comment]
Cool - do you want to apply this to the later ICP check too, or leave that as just ICP > 10?

**Comment by camerondeleone** [comment]
> Cool - do you want to apply this to the later ICP check too, or leave that as just ICP > 10?

I ended up getting rid of it because too few people have that property set from what I can tell, and it seemed to be missing out on a bunch of good potential customers. I also feel like there's a large contingent of users with no hubspot score 
image
 so just set [this](https://fly.customer.io/workspaces/127208/journeys/campaigns/58/overview) up which hopefully does help...

**Comment by joethreepwood** [comment]
> I ended up getting rid of it because too few people have that property set from what I can tell

Not sure I follow this, as I can't see either of those segments used anywhere? 

The Onboarding flow currently still checks for ICP > 10 (via `Hubspot_score`) before the welcome email, and before the upsell cycle, but that's it.

**Pull request merged**
