### PR TITLE
RFC: Automate G2 requests

### PR DESCRIPTION
**Pull request by joethreepwood**
Owner: @joethreepwood (Marketing)
Decision to be made: Should I enable this campaign?
Decision date: 13 Jan 2023

### CODE REVIEW

**Comment by charlescook-ph** [comment]
Seems like an obvious yes to the process! What does the email itself look like coming out of customer.io?

**Comment by joethreepwood** [comment]
> Seems like an obvious yes to the process! What does the email itself look like coming out of customer.io?

Basically identical to the Mailchimp one. 

g2-email-1

**Comment by joethreepwood** [comment]
> Seems like an obvious yes to the process! What does the email itself look like coming out of customer.io?

Basically identical to the Mailchimp one. 

g2-email-1

**Review by andyvan-ph — APPROVED** [review]

**Comment by joethreepwood** [comment]
Right then, merging this and enabling the flow.

**Pull request merged**
