### PR TITLE
RFC: Daily onboarding emails for users

### PR DESCRIPTION
**Pull request by joethreepwood**
Going to get started putting this together because an opt-in flow feels uncontroversial, but thoughts appreciated. 

Especially interested in thoughts from @MarconLP about common setup issues or questions we can head off here.

### CODE REVIEW

**Comment by charlescook-ph** [comment]
Making it opt in is interesting - you could frame it in a fun way potentially as like a micro-course or something too? (Beyond just 'hey sign up for daily tips'). 

But happy to try this as an experiment and see what happens!

**Comment by MarconLP** [comment]
I like this idea and the content covers the most common issues. I think `setting up the reverse proxy` should be the first email, to avoid "I don't see events in PostHog" tickets for users with an installed AdBlock extension.

**Comment by joethreepwood** [comment]
Launched this. Will report back with metrics in a few weeks.

**Comment by joethreepwood** [comment]
Just for transparency, we have deactivated this campaign today after only seeing 11 users sign up for it.

**Pull request merged**
